import os                                # Check whether the RDF .ttl file exists
import xml.etree.ElementTree as ET       # Read XML file, especially skill names and aliases
from difflib import get_close_matches    # Suggest closest skill spelling, like pyhton → Python

from rdflib import Graph, Namespace      # Graph      - Load and query the RDF Turtle graph
                                         # Namespace  - Define RDF namespace, such as ex:

import tkinter as tk                     # Create the popup GUI window

from tkinter import ttk, messagebox      # ttk        - Create nicer widgets, such as dropdown combobox
                                         # messagebox - Show popup messages, warnings, errors, and confirmation boxes


# ------------------------------------------------------------
# TSW6223 Solution 2 GUI Application
#
# Purpose:
# This file provides a simple popup window interface for the
# Semantic Career Path / Skill Gap Analyzer.
#
# The backend still uses:
# - XML for skill aliases and input normalisation
# - RDF/RDFS Turtle file for semantic data
# - SPARQL queries to retrieve careers, required skills,
#   recommended courses, and alternative careers
#
# This GUI is launched after main.py completes:
# 1. XML validation
# 2. XML to RDF/RDFS conversion
# 3. SPARQL proof queries
# ------------------------------------------------------------


XML_FILE = "career_skill_data.xml"
TTL_FILE = "career_skill_graph.ttl"

# Reading XML with namespace. 
# The namespace prefix "cs" is defined in the XML file and used to access elements.
XML_NS   = {"cs": "https://tsw6223.example.edu/career-skill"}

# Defines your RDF namespace. 
# This is used in SPARQL queries and when working with RDF data.
EX       = Namespace("http://example.org/career-skill#")


def get_text(parent, tag_name):
    """
    Helper Function:
    Safely get text from an XML child element.
    This is mainly used to read skill names and aliases from XML.
    """
    element = parent.find(f"cs:{tag_name}", XML_NS)

    if element is not None and element.text is not None:
        return element.text.strip()

    return ""


def load_rdf_graph():
    """
    Load the generated RDF/RDFS Turtle graph.

    This graph is generated by xml_to_rdf.py and contains semantic
    relationships such as:
    - Career requires Skill
    - Course teaches Skill
    - Course has prerequisite Skill
    """
    if not os.path.exists(TTL_FILE):
        messagebox.showerror(
            "Missing RDF File",
            f"{TTL_FILE} was not found.\nPlease run py main.py first."
        )
        return None

    # Load the RDF graph from the Turtle file.
    graph = Graph()
    graph.parse(TTL_FILE, format="turtle")
    return graph


def load_skill_aliases_from_xml():
    """
    Load official skill names and aliases from XML.

    Example:
    - "py" maps to "Python"
    - "ml" maps to "Machine Learning"
    - "pyhton" maps to "Python"

    This helps the system handle user input before SPARQL-based analysis.
    1) The system reads the alias elements from the XML file that we prepared. 
    2) Then it stores the official skill names in a list and stores the alias-to-skill mappings in a dictionary. 
    3) Later, when the user enters skills in the GUI, Python uses this dictionary to convert inputs such as 
       "py", "ml", or "pyhton" into the official skill names such as "Python" and "Machine Learning".
    """
    tree = ET.parse(XML_FILE)
    root = tree.getroot()

    skill_names = [] # Stores official skill names.
    alias_map = {}   # Stores aliases and maps them to official skill names.

    for skill in root.findall("cs:skills/cs:skill", XML_NS):
        skill_name = get_text(skill, "skillName")
        skill_names.append(skill_name)

        # Map official skill name to itself.
        alias_map[skill_name.lower()] = skill_name

        # Map each alias to the official skill name.
        for alias in skill.findall("cs:aliases/cs:alias", XML_NS):
            if alias.text:
                alias_map[alias.text.strip().lower()] = skill_name

    return skill_names, alias_map


def clean_user_input(user_input):
    """
    Clean comma-separated skill input.

    Example:
    Input:  " pyhton, SQL, ml "
    Output: ["pyhton", "sql", "ml"]
    """
    cleaned_items = []

    for item in user_input.split(","):
        
        # Remove leading/trailing whitespace and convert to lowercase for consistent matching.
        cleaned = item.strip().lower() 

        if cleaned:
            cleaned_items.append(cleaned)

    return cleaned_items


def normalise_skills(user_input, skill_names, alias_map):
    """
    Convert user-entered skills into official skill names.

    The GUI version uses:
    1. Alias matching
    2. Fuzzy typo matching
    3. Popup confirmation for suggested correction
    """
    cleaned_inputs = clean_user_input(user_input)

    confirmed_skills = [] # Stores skills that the system recognises.
    unknown_skills = []   # Stores inputs that cannot be matched.

    official_skill_lookup = {name.lower(): name for name in skill_names}
    official_skill_lowercase = list(official_skill_lookup.keys())

    for item in cleaned_inputs:

        # Exact alias match, e.g. "ml" -> "Machine Learning"
        if item in alias_map:
            official_skill = alias_map[item]

            if official_skill not in confirmed_skills:
                confirmed_skills.append(official_skill)

        else:
            # Fuzzy matching, e.g. "pythn" may suggest "Python"
            possible_matches = get_close_matches(
                item,
                official_skill_lowercase,
                n=1,        # means return only the best match.
                cutoff=0.7  # means the match must be quite similar.

                # If the word similarity is too low, it will not suggest anything.
            )

            # If a close match is found, the GUI shows a popup.
            if possible_matches:
                suggested_skill = official_skill_lookup[possible_matches[0]]

                accept = messagebox.askyesno(
                    "Skill Correction",
                    f'"{item}" was not found.\n\nDid you mean "{suggested_skill}"?'
                )

                if accept:
                    if suggested_skill not in confirmed_skills:
                        confirmed_skills.append(suggested_skill)
                else:
                    # If the user clicks No, then the original input is stored as unknown.
                    unknown_skills.append(item)
            else:
                # If there is no alias match and no fuzzy match, the skill is stored as unknown.
                unknown_skills.append(item)

    return confirmed_skills, unknown_skills


def get_available_careers(graph):
    """
    Retrieve available careers from the RDF graph using SPARQL.

    This means the career list shown in the GUI is not hard-coded.
    It is retrieved from semantic RDF data.

    Note: a - is a shorthand for rdf:type, which indicates the type of the resource.
    """
    query = """
    PREFIX ex: <http://example.org/career-skill#>

    SELECT ?career ?careerName ?sourceTitle ?sourceCode ?careerLevel
    WHERE {
        ?career a ex:Career .
        ?career ex:careerName ?careerName .
        ?career ex:sourceOccupationTitle ?sourceTitle .
        ?career ex:sourceOccupationCode ?sourceCode .
        ?career ex:careerLevel ?careerLevel .
    }
    ORDER BY ?careerName
    """

    careers = []   # Creates an empty list to store the careers.

    for row in graph.query(query):
        careers.append({
            "career_uri": str(row.career),        # Used by the get_required_skills_for_career(graph, career_uri)'s career_uri
            "career_name": str(row.careerName),
            "source_title": str(row.sourceTitle),
            "source_code": str(row.sourceCode),
            "career_level": str(row.careerLevel)
        })

    return careers


def get_required_skills_for_career(graph, career_uri):
    """
    Retrieve required skills for the selected career using SPARQL.

    This query also retrieves:
    - skill category
    - skill priority
    """
    query = """
    PREFIX ex: <http://example.org/career-skill#>

    SELECT ?skill ?skillName ?skillCategory ?priority
    WHERE {
        <CAREER_URI> ex:requiresSkill ?skill .

        ?skill ex:skillName ?skillName .

        ?skill ex:skillCategory ?skillCategory .

        ?requirement a ex:SkillRequirement .
        ?requirement ex:requirementForCareer <CAREER_URI> .
        ?requirement ex:requiresSkill ?skill .
        ?requirement ex:priority ?priority .
    }
    ORDER BY ?priority ?skillName
    """.replace("CAREER_URI", career_uri)

    required_skills = []

    for row in graph.query(query):
        required_skills.append({
            "skill_uri": str(row.skill),
            "skill_name": str(row.skillName),
            "category": str(row.skillCategory),
            "priority": str(row.priority)
        })

    return required_skills


def analyse_skill_gap(required_skills, confirmed_skills):
    """
    Compare confirmed user skills with SPARQL-retrieved required skills.

    Note: 
    - The required_skills and confirmed_skills are from previous code.
    """
    matched_skills = []
    missing_skills = []

    for skill in required_skills:
        if skill["skill_name"] in confirmed_skills:
            matched_skills.append(skill)
        else:
            missing_skills.append(skill)

    total_required = len(required_skills)
    total_matched = len(matched_skills)

    if total_required > 0:
        readiness_score = round((total_matched / total_required) * 100)
    else:
        readiness_score = 0

    return matched_skills, missing_skills, readiness_score


def get_courses_for_missing_skills(graph, missing_skills):
    """
    Retrieve recommended courses using SPARQL.

    This query uses the SPARQL VALUES clause to inject the missing skills
    directly into the query, filtering courses at the graph database level.
    """
    if not missing_skills:
        return []

    # Format missing skills for SPARQL (e.g., "Python" "Machine Learning")
    skill_names_str = " ".join([f'"{skill["skill_name"]}"' for skill in missing_skills])

    query = f"""
    PREFIX ex: <http://example.org/career-skill#>

    SELECT ?course ?courseName ?skillName ?prerequisiteName
    WHERE {{
        # This forces SPARQL to ONLY look for these specific missing skills
        VALUES ?skillName {{ {skill_names_str} }} 

        ?course a ex:Course .
        ?course ex:courseName ?courseName .
        ?course ex:teachesSkill ?skill .
        ?skill ex:skillName ?skillName .

        OPTIONAL {{
            ?course ex:prerequisiteSkill ?prerequisite .
            ?prerequisite ex:skillName ?prerequisiteName .
        }}
    }}
    ORDER BY ?courseName ?skillName
    """

    recommended = {}

    for row in graph.query(query):
        skill_name = str(row.skillName)
        course_uri = str(row.course)
        course_name = str(row.courseName)

        # If this course is not already in the recommended dictionary, 
        # add it with empty lists for teaches_missing_skills and prerequisite_skills.
        if course_uri not in recommended:
            recommended[course_uri] = {
                "course_name": course_name,
                "teaches_missing_skills": [],
                "prerequisite_skills": []
            }

        # If the course teaches a missing skill, add it to the teaches_missing_skills list for that course.
        if skill_name not in recommended[course_uri]["teaches_missing_skills"]:
            recommended[course_uri]["teaches_missing_skills"].append(skill_name)

        # If there is a prerequisite skill, add it to the prerequisite_skills list for that course.
        if row.prerequisiteName:
            prerequisite_name = str(row.prerequisiteName)

            if prerequisite_name not in recommended[course_uri]["prerequisite_skills"]:
                recommended[course_uri]["prerequisite_skills"].append(prerequisite_name)

    # Converts the dictionary into a list. 
    # Each item in the list is a dictionary containing course_name, teaches_missing_skills, and prerequisite_skills.
    return list(recommended.values())


def suggest_alternative_careers(graph, selected_career_uri, confirmed_skills):
    """
    Retrieve career-skill relationships using SPARQL and calculate
    match percentage for alternative careers.

    This query filters out the selected target career at the SPARQL graph level.
    """
    query = f"""
    PREFIX ex: <http://example.org/career-skill#>

    SELECT ?career ?careerName ?skillName
    WHERE {{
        ?career a ex:Career .
        ?career ex:careerName ?careerName .

        # Exclude the currently selected career at the graph level
        FILTER(?career != <{selected_career_uri}>)

        ?career ex:requiresSkill ?skill .
        ?skill ex:skillName ?skillName .
    }}
    ORDER BY ?careerName ?skillName
    """

    career_skill_map = {}

    for row in graph.query(query):
        career_uri = str(row.career)
        career_name = str(row.careerName)
        skill_name = str(row.skillName)

        if career_uri not in career_skill_map:
            career_skill_map[career_uri] = {
                "career_name": career_name,
                "required_skills": []
            }

        career_skill_map[career_uri]["required_skills"].append(skill_name)

    alternatives = []

    for career_uri, career_data in career_skill_map.items():
        required_skills = career_data["required_skills"]
        matched_count = 0

        for skill_name in required_skills:
            if skill_name in confirmed_skills:
                matched_count += 1

        if required_skills:
            match_score = round((matched_count / len(required_skills)) * 100)
        else:
            match_score = 0

        alternatives.append({
            "career_name": career_data["career_name"],
            "match_score": match_score
        })

    # Sorts alternative careers from highest match to lowest match.
    alternatives.sort(key=lambda item: item["match_score"], reverse=True)

    return alternatives


def group_missing_skills_by_priority(missing_skills):
    """
    Group missing skills into High, Medium, and Low priority.

    Mainly for output formatting in the GUI, so that users can see which missing skills are most important.
    """
    grouped = {
        "High": [],
        "Medium": [],
        "Low": []
    }

    for skill in missing_skills:
        priority = skill["priority"]

        if priority in grouped:
            grouped[priority].append(skill)
        else:
            grouped["Low"].append(skill)

    return grouped


def format_result(
    selected_career,     # Career chosen by the user
    confirmed_skills,    # User skills successfully recognised
    unknown_skills,      # User inputs that could not be matched
    required_skills,     # Skills required by selected career
    matched_skills,      # Required skills the user already has
    missing_skills,      # Required skills the user does not have
    readiness_score,     # Match percentage
    recommended_courses, # Courses for missing skills
    alternative_careers  # Other careers with match score
):
    """
    Format the analysis result into readable text for the GUI output box.
    """
    lines = []           # Stores each line of the output text.

    lines.append("===== Semantic Career Path / Skill Gap Analyzer =====")
    lines.append("")
    lines.append(f"Target Career: {selected_career['career_name']}")
    lines.append(f"O*NET Source Title: {selected_career['source_title']}")
    lines.append(f"O*NET Code: {selected_career['source_code']}")
    lines.append(f"Career Level: {selected_career['career_level']}")
    lines.append("")
    # The f prefix before the quotes tells Python to replace 
    # anything inside {} curly braces with its actual value at runtime.

    lines.append("Confirmed Current Skills:")
    if confirmed_skills:
        for skill in confirmed_skills:
            lines.append(f"- {skill}")
    else:
        lines.append("- None")

    if unknown_skills:
        lines.append("")
        lines.append("Unknown / Unmatched Inputs:")
        for skill in unknown_skills:
            lines.append(f"- {skill}")

    lines.append("")
    lines.append("Required Skills Retrieved Using SPARQL:")
    for skill in required_skills:
        lines.append(f"- {skill['skill_name']} ({skill['priority']}, {skill['category']})")

    lines.append("")
    lines.append("Matched Skills:")
    if matched_skills:
        for skill in matched_skills:
            lines.append(f"- {skill['skill_name']}")
    else:
        lines.append("- None")

    lines.append("")
    lines.append("Missing Skills by Priority:")
    grouped_missing = group_missing_skills_by_priority(missing_skills)

    # Check whether the user has any missing skills.
    has_missing = False 

    for priority in ["High", "Medium", "Low"]:
        if grouped_missing[priority]:
            has_missing = True
            lines.append("")
            lines.append(f"[{priority.upper()}]")
            for skill in grouped_missing[priority]:
                lines.append(f"- {skill['skill_name']} ({skill['category']})")

    if not has_missing:
        lines.append("- No missing skills. You meet all listed requirements.")

    lines.append("")
    lines.append(f"Career Readiness Score: {readiness_score}%")

    lines.append("")
    lines.append("Recommended Learning Path Retrieved Using SPARQL:")
    if recommended_courses:
        for index, course in enumerate(recommended_courses, start=1):
            taught = ", ".join(course["teaches_missing_skills"])
            lines.append(f"{index}. {course['course_name']}")
            lines.append(f"   Reason: This course teaches missing skill(s): {taught}.")

            if course["prerequisite_skills"]:
                prerequisites = ", ".join(course["prerequisite_skills"])
                lines.append(f"   Prerequisite skill(s): {prerequisites}.")
            else:
                lines.append("   Prerequisite skill(s): None.")
    else:
        lines.append("- No course recommendation needed.")

    lines.append("")
    lines.append("Alternative Career Suggestions Retrieved Using SPARQL:")
    if alternative_careers:
        for index, career in enumerate(alternative_careers, start=1):
            lines.append(f"{index}. {career['career_name']} - {career['match_score']}% match")
    else:
        lines.append("- No alternative careers available.")

    # Combines all lines into one text block.
    return "\n".join(lines)


class SkillGapGUI:
    """
    Main GUI class.

    This class creates the popup window and connects button actions
    to the SPARQL-powered skill gap analysis functions.
    
    - self means the SkillGapGUI object's own data.
    """

    def __init__(self, root):                                                  # The setup function for the GUI.
        self.root = root                                                       # The root variable is the main window of the GUI, which is passed in when the SkillGapGUI object is created in the main() function.
        self.root.title("TSW6223 Semantic Career Path / Skill Gap Analyzer")   # Set the title of the GUI window.
        self.root.geometry("900x700")                                          # Set the default size of the GUI window (width x height in pixels).

        self.graph = load_rdf_graph()
        self.skill_names, self.alias_map = load_skill_aliases_from_xml()

        # Error handling: If the RDF graph cannot be loaded, show an error message and close the GUI.
        if self.graph is None:
            self.root.destroy()
            return

        self.careers = get_available_careers(self.graph)

        # Creates the visible GUI elements.
        self.create_widgets()

    def create_widgets(self):
        """
        Create all GUI components.
        """
        title_label = tk.Label(
            self.root,
            text="Semantic Career Path / Skill Gap Analyzer",
            font=("Arial", 18, "bold")
        )
        title_label.pack(pady=10)

        # Create instruction label to guide the user on how to use the GUI.
        instruction_label = tk.Label(
            self.root,
            text="Select a target career and enter your current skills separated by commas.",
            font=("Arial", 11)
        )
        instruction_label.pack(pady=5)

        # Create form frame 
        form_frame = tk.Frame(self.root)
        form_frame.pack(pady=10)

        # Career #
        career_label = tk.Label(form_frame, text="Target Career:", font=("Arial", 11))
        career_label.grid(row=0, column=0, padx=5, pady=5, sticky="e")

        # The dropdown list is based on RDF/SPARQL career data, not hard-coded manually.
        career_names = [career["career_name"] for career in self.careers]

        self.career_combo = ttk.Combobox(
            form_frame,
            values=career_names,
            width=40,
            state="readonly"
        )
        self.career_combo.grid(row=0, column=1, padx=5, pady=5)

        # Selects the first career by default.
        if career_names:
            self.career_combo.current(0)

        # Skills #
        skills_label = tk.Label(form_frame, text="Current Skills:", font=("Arial", 11))
        skills_label.grid(row=1, column=0, padx=5, pady=5, sticky="e")

        self.skills_entry = tk.Entry(form_frame, width=45)
        self.skills_entry.grid(row=1, column=1, padx=5, pady=5)
        self.skills_entry.insert(0, "pyhton, sql, ml")

        # Analyse Button #
        analyse_button = tk.Button(
            self.root,
            text="Analyse Skill Gap",
            font=("Arial", 11, "bold"),
            command=self.run_analysis
        )
        analyse_button.pack(pady=10)

        # Output Text Box #
        self.output_text = tk.Text(
            self.root,
            wrap="word",
            width=105,
            height=30
        )
        self.output_text.pack(padx=15, pady=10, fill="both", expand=True)

    def get_selected_career(self):
        """
        Get the selected career object from the dropdown list.
        """
        selected_name = self.career_combo.get()

        for career in self.careers:
            if career["career_name"] == selected_name:
                return career

        return None

    def run_analysis(self):
        """
        Run the full analysis when the user clicks the button.
        """
        selected_career = self.get_selected_career()

        if selected_career is None:
            messagebox.showerror("Selection Error", "Please select a valid career.")
            return

        user_input = self.skills_entry.get()

        if not user_input.strip():
            messagebox.showwarning("Missing Input", "Please enter at least one skill.")
            return

        confirmed_skills, unknown_skills = normalise_skills(
            user_input,
            self.skill_names,
            self.alias_map
        )

        required_skills = get_required_skills_for_career(
            self.graph,
            selected_career["career_uri"]
        )

        matched_skills, missing_skills, readiness_score = analyse_skill_gap(
            required_skills,
            confirmed_skills
        )

        recommended_courses = get_courses_for_missing_skills(
            self.graph,
            missing_skills
        )

        alternative_careers = suggest_alternative_careers(
            self.graph,
            selected_career["career_uri"],
            confirmed_skills
        )

        result_text = format_result(
            selected_career,
            confirmed_skills,
            unknown_skills,
            required_skills,
            matched_skills,
            missing_skills,
            readiness_score,
            recommended_courses,
            alternative_careers
        )

        self.output_text.delete("1.0", tk.END)        # Delete old result
        self.output_text.insert(tk.END, result_text)  # Insert new result


def main():
    """
    Start the popup GUI application.
    """
    root = tk.Tk()           # Creates the main GUI window. (Enpty window)

    app = SkillGapGUI(root)  # Creates an object from the self-defined class (class SkillGapGUI)
                             # - Fills that empty window with the actual GUI design and logic.
   
    root.mainloop()          # Keep the GUI window open and wait for user actions.


if __name__ == "__main__":
    main()