import os
import xml.etree.ElementTree as ET
from difflib import get_close_matches
from rdflib import Graph, Namespace, URIRef


# ------------------------------------------------------------
# TSW6223 Solution 2: SPARQL-powered Skill Gap Analysis
#
# Purpose:
# This file performs the final career path / skill gap analysis.
#
# Improvement:
# Earlier versions used Python dictionaries extracted directly
# from XML for most analysis. This version retrieves important
# semantic relationships from the RDF graph using SPARQL.
#
# SPARQL is now used to retrieve:
# 1. Available careers
# 2. Skills required by a selected career
# 3. Courses that teach missing skills
# 4. Course prerequisite skills
# 5. Alternative career match information
#
# Python is still used for:
# 1. User input handling
# 2. Alias matching and typo correction
# 3. Readiness score calculation
# 4. Terminal display formatting
# ------------------------------------------------------------


XML_FILE = "career_skill_data.xml"
TTL_FILE = "career_skill_graph.ttl"

# XML namespace used for reading aliases from the XML file.
XML_NS = {"cs": "https://tsw6223.example.edu/career-skill"}

# RDF namespace used in career_skill_graph.ttl.
EX = Namespace("http://example.org/career-skill#")


def get_text(parent, tag_name):
    """
    Safely get text from an XML child element.

    This is used only for reading skill aliases from XML.
    The main career/course analysis will use SPARQL.
    """
    element = parent.find(f"cs:{tag_name}", XML_NS)

    if element is not None and element.text is not None:
        return element.text.strip()

    return ""


def load_rdf_graph():
    """
    Load the RDF Turtle graph generated by xml_to_rdf.py.

    The TTL file contains semantic triples such as:
    - AIEngineer requiresSkill Python
    - MachineLearningFundamentals teachesSkill MachineLearning
    - DataVisualizationFundamentals prerequisiteSkill Statistics
    """

    if not os.path.exists(TTL_FILE):
        print(f"Error: {TTL_FILE} was not found.")
        print("Please run: py xml_to_rdf.py")
        return None

    graph = Graph()
    graph.parse(TTL_FILE, format="turtle")

    return graph


def load_skill_aliases_from_xml():
    """
    Load skill names and aliases from the XML file.

    Why XML is still used here:
    User input normalisation is a pre-processing task.
    The XML file stores aliases such as:
    - py -> Python
    - ml -> Machine Learning
    - pyhton -> Python

    Return:
    skill_names:
        List of official skill names.

    alias_map:
        Dictionary that maps user input to official skill names.
    """

    tree = ET.parse(XML_FILE)
    root = tree.getroot()

    skill_names = []
    alias_map = {}

    for skill in root.findall("cs:skills/cs:skill", XML_NS):
        skill_name = get_text(skill, "skillName")

        skill_names.append(skill_name)

        # Map official skill name to itself.
        # Example: "python" -> "Python"
        alias_map[skill_name.lower()] = skill_name

        # Map all aliases to the official skill name.
        for alias in skill.findall("cs:aliases/cs:alias", XML_NS):
            if alias.text:
                alias_map[alias.text.strip().lower()] = skill_name

    return skill_names, alias_map


def clean_user_input(user_input):
    """
    Clean comma-separated user input.

    Example:
    Input:  " pyhton, SQL, ml "
    Output: ["pyhton", "sql", "ml"]
    """

    cleaned_items = []

    for item in user_input.split(","):
        cleaned = item.strip().lower()

        if cleaned:
            cleaned_items.append(cleaned)

    return cleaned_items


def normalise_skills(user_input, skill_names, alias_map):
    """
    Convert user-entered skills into official skill names.

    This supports:
    1. Exact alias matching
    2. Fuzzy typo matching
    3. User confirmation for typo suggestions
    """

    cleaned_inputs = clean_user_input(user_input)

    confirmed_skills = []
    unknown_skills = []

    official_skill_lookup = {name.lower(): name for name in skill_names}
    official_skill_lowercase = list(official_skill_lookup.keys())

    print("\n===== Input Validation =====")

    for item in cleaned_inputs:

        # Step 1: Exact alias matching.
        # Example: "ml" -> "Machine Learning"
        if item in alias_map:
            official_skill = alias_map[item]
            print(f'- "{item}" matched to "{official_skill}"')

            if official_skill not in confirmed_skills:
                confirmed_skills.append(official_skill)

        else:
            # Step 2: Fuzzy matching for spelling mistakes.
            # Example: "pythn" may suggest "Python".
            possible_matches = get_close_matches(
                item,
                official_skill_lowercase,
                n=1,
                cutoff=0.7
            )

            if possible_matches:
                suggested_skill = official_skill_lookup[possible_matches[0]]

                print(f'- "{item}" was not found. Did you mean "{suggested_skill}"?')
                user_confirm = input("  Enter Y to accept, or N to reject: ").strip().lower()

                if user_confirm == "y":
                    if suggested_skill not in confirmed_skills:
                        confirmed_skills.append(suggested_skill)

                    print(f'  Accepted: "{item}" -> "{suggested_skill}"')
                else:
                    unknown_skills.append(item)
                    print(f'  Rejected: "{item}" was marked as unknown.')
            else:
                unknown_skills.append(item)
                print(f'- "{item}" could not be matched to any known skill.')

    return confirmed_skills, unknown_skills


def get_available_careers(graph):
    """
    Use SPARQL to retrieve all available careers from the RDF graph.

    This proves that career options are no longer hard-coded in Python.
    They are retrieved from RDF triples.
    """

    query = """
    PREFIX ex: <http://example.org/career-skill#>

    SELECT ?career ?careerName ?sourceTitle ?sourceCode ?careerLevel
    WHERE {
        ?career a ex:Career .
        ?career ex:careerName ?careerName .
        ?career ex:sourceOccupationTitle ?sourceTitle .
        ?career ex:sourceOccupationCode ?sourceCode .
        ?career ex:careerLevel ?careerLevel .
    }
    ORDER BY ?careerName
    """

    careers = []

    for row in graph.query(query):
        careers.append({
            "career_uri": str(row.career),
            "career_name": str(row.careerName),
            "source_title": str(row.sourceTitle),
            "source_code": str(row.sourceCode),
            "career_level": str(row.careerLevel)
        })

    return careers


def select_target_career(graph):
    """
    Display careers retrieved by SPARQL and allow the user to select one.
    """

    careers = get_available_careers(graph)

    print("\n===== Available Careers Retrieved Using SPARQL =====")

    for index, career in enumerate(careers, start=1):
        print(f"{index}. {career['career_name']}")

    while True:
        try:
            choice = int(input("\nSelect your target career number: "))

            if 1 <= choice <= len(careers):
                return careers[choice - 1]

            print("Invalid choice. Please select a valid career number.")

        except ValueError:
            print("Invalid input. Please enter a number.")


def get_required_skills_for_career(graph, career_uri):
    """
    Use SPARQL to retrieve the skills required by the selected career.

    This query also retrieves:
    - skill category
    - priority level

    The priority is stored in the SkillRequirement node that was
    generated during XML-to-RDF conversion.
    """

    query = """
    PREFIX ex: <http://example.org/career-skill#>

    SELECT ?skill ?skillName ?skillCategory ?priority
    WHERE {
        <CAREER_URI> ex:requiresSkill ?skill .

        ?skill ex:skillName ?skillName .
        ?skill ex:skillCategory ?skillCategory .

        ?requirement a ex:SkillRequirement .
        ?requirement ex:requirementForCareer <CAREER_URI> .
        ?requirement ex:requiresSkill ?skill .
        ?requirement ex:priority ?priority .
    }
    ORDER BY ?priority ?skillName
    """.replace("CAREER_URI", career_uri)

    required_skills = []

    for row in graph.query(query):
        required_skills.append({
            "skill_uri": str(row.skill),
            "skill_name": str(row.skillName),
            "category": str(row.skillCategory),
            "priority": str(row.priority)
        })

    return required_skills


def analyse_skill_gap(required_skills, confirmed_skills):
    """
    Compare confirmed user skills with SPARQL-retrieved career skills.

    Return:
    - matched skills
    - missing skills
    - readiness score
    """

    matched_skills = []
    missing_skills = []

    for skill in required_skills:
        if skill["skill_name"] in confirmed_skills:
            matched_skills.append(skill)
        else:
            missing_skills.append(skill)

    total_required = len(required_skills)
    total_matched = len(matched_skills)

    if total_required > 0:
        readiness_score = round((total_matched / total_required) * 100)
    else:
        readiness_score = 0

    return matched_skills, missing_skills, readiness_score


def get_courses_for_missing_skills(graph, missing_skills):
    """
    Use SPARQL to retrieve courses that teach missing skills.

    The query retrieves all course-skill-prerequisite relationships.
    Python then filters the result based on the missing skills list.
    """

    missing_skill_names = [skill["skill_name"] for skill in missing_skills]

    query = """
    PREFIX ex: <http://example.org/career-skill#>

    SELECT ?course ?courseName ?skillName ?prerequisiteName
    WHERE {
        ?course a ex:Course .
        ?course ex:courseName ?courseName .
        ?course ex:teachesSkill ?skill .
        ?skill ex:skillName ?skillName .

        OPTIONAL {
            ?course ex:prerequisiteSkill ?prerequisite .
            ?prerequisite ex:skillName ?prerequisiteName .
        }
    }
    ORDER BY ?courseName ?skillName
    """

    recommended = {}

    for row in graph.query(query):
        skill_name = str(row.skillName)

        # Only recommend the course if it teaches a missing skill.
        if skill_name in missing_skill_names:
            course_uri = str(row.course)
            course_name = str(row.courseName)

            if course_uri not in recommended:
                recommended[course_uri] = {
                    "course_name": course_name,
                    "teaches_missing_skills": [],
                    "prerequisite_skills": []
                }

            if skill_name not in recommended[course_uri]["teaches_missing_skills"]:
                recommended[course_uri]["teaches_missing_skills"].append(skill_name)

            # Optional values may be empty, so check before adding.
            if row.prerequisiteName:
                prerequisite_name = str(row.prerequisiteName)

                if prerequisite_name not in recommended[course_uri]["prerequisite_skills"]:
                    recommended[course_uri]["prerequisite_skills"].append(prerequisite_name)

    return list(recommended.values())


def suggest_alternative_careers(graph, selected_career_uri, confirmed_skills):
    """
    Use SPARQL to retrieve all career-skill relationships.

    Python then calculates the match percentage for each alternative career.
    """

    query = """
    PREFIX ex: <http://example.org/career-skill#>

    SELECT ?career ?careerName ?skillName
    WHERE {
        ?career a ex:Career .
        ?career ex:careerName ?careerName .
        ?career ex:requiresSkill ?skill .
        ?skill ex:skillName ?skillName .
    }
    ORDER BY ?careerName ?skillName
    """

    career_skill_map = {}

    for row in graph.query(query):
        career_uri = str(row.career)
        career_name = str(row.careerName)
        skill_name = str(row.skillName)

        if career_uri not in career_skill_map:
            career_skill_map[career_uri] = {
                "career_name": career_name,
                "required_skills": []
            }

        career_skill_map[career_uri]["required_skills"].append(skill_name)

    alternatives = []

    for career_uri, career_data in career_skill_map.items():

        # Do not suggest the career that the user already selected.
        if career_uri == selected_career_uri:
            continue

        required_skills = career_data["required_skills"]

        matched_count = 0

        for skill_name in required_skills:
            if skill_name in confirmed_skills:
                matched_count += 1

        if required_skills:
            match_score = round((matched_count / len(required_skills)) * 100)
        else:
            match_score = 0

        alternatives.append({
            "career_name": career_data["career_name"],
            "match_score": match_score
        })

    alternatives.sort(key=lambda item: item["match_score"], reverse=True)

    return alternatives


def group_missing_skills_by_priority(missing_skills):
    """
    Group missing skills by priority level for cleaner output.
    """

    grouped = {
        "High": [],
        "Medium": [],
        "Low": []
    }

    for skill in missing_skills:
        priority = skill["priority"]

        if priority in grouped:
            grouped[priority].append(skill)
        else:
            grouped["Low"].append(skill)

    return grouped


def print_analysis_result(
    selected_career,
    confirmed_skills,
    unknown_skills,
    required_skills,
    matched_skills,
    missing_skills,
    readiness_score,
    recommended_courses,
    alternative_careers
):
    """
    Print the final result in a clear terminal format.
    """

    print("\n\n===== Semantic Career Path / Skill Gap Analyzer =====")

    print(f"\nTarget Career: {selected_career['career_name']}")
    print(f"O*NET Source Title: {selected_career['source_title']}")
    print(f"O*NET Code: {selected_career['source_code']}")
    print(f"Career Level: {selected_career['career_level']}")

    print("\nConfirmed Current Skills:")
    if confirmed_skills:
        for skill in confirmed_skills:
            print(f"- {skill}")
    else:
        print("- None")

    if unknown_skills:
        print("\nUnknown / Unmatched Inputs:")
        for skill in unknown_skills:
            print(f"- {skill}")

    print("\nRequired Skills Retrieved Using SPARQL:")
    for skill in required_skills:
        print(f"- {skill['skill_name']} ({skill['priority']}, {skill['category']})")

    print("\nMatched Skills:")
    if matched_skills:
        for skill in matched_skills:
            print(f"- {skill['skill_name']}")
    else:
        print("- None")

    print("\nMissing Skills by Priority:")
    grouped_missing = group_missing_skills_by_priority(missing_skills)

    has_missing = False

    for priority in ["High", "Medium", "Low"]:
        if grouped_missing[priority]:
            has_missing = True
            print(f"\n[{priority.upper()}]")
            for skill in grouped_missing[priority]:
                print(f"- {skill['skill_name']} ({skill['category']})")

    if not has_missing:
        print("- No missing skills. You meet all listed requirements.")

    print(f"\nCareer Readiness Score: {readiness_score}%")

    print("\nRecommended Learning Path Retrieved Using SPARQL:")
    if recommended_courses:
        for index, course in enumerate(recommended_courses, start=1):
            taught_skills = ", ".join(course["teaches_missing_skills"])
            prerequisites = course["prerequisite_skills"]

            print(f"{index}. {course['course_name']}")
            print(f"   Reason: This course teaches missing skill(s): {taught_skills}.")

            if prerequisites:
                print(f"   Prerequisite skill(s): {', '.join(prerequisites)}.")
            else:
                print("   Prerequisite skill(s): None.")
    else:
        print("- No course recommendation needed.")

    print("\nAlternative Career Suggestions Retrieved Using SPARQL:")
    if alternative_careers:
        for index, career in enumerate(alternative_careers, start=1):
            print(f"{index}. {career['career_name']} - {career['match_score']}% match")
    else:
        print("- No alternative careers available.")


def main():
    """
    Main program flow for the SPARQL-powered skill gap analyzer.
    """

    graph = load_rdf_graph()

    if graph is None:
        return

    skill_names, alias_map = load_skill_aliases_from_xml()

    selected_career = select_target_career(graph)

    print("\nEnter your current skills separated by comma.")
    print("Example: pyhton, sql, ml")
    user_input = input("Your skills: ")

    confirmed_skills, unknown_skills = normalise_skills(
        user_input,
        skill_names,
        alias_map
    )

    required_skills = get_required_skills_for_career(
        graph,
        selected_career["career_uri"]
    )

    matched_skills, missing_skills, readiness_score = analyse_skill_gap(
        required_skills,
        confirmed_skills
    )

    recommended_courses = get_courses_for_missing_skills(
        graph,
        missing_skills
    )

    alternative_careers = suggest_alternative_careers(
        graph,
        selected_career["career_uri"],
        confirmed_skills
    )

    print_analysis_result(
        selected_career,
        confirmed_skills,
        unknown_skills,
        required_skills,
        matched_skills,
        missing_skills,
        readiness_score,
        recommended_courses,
        alternative_careers
    )


if __name__ == "__main__":
    main()