import os
import xml.etree.ElementTree as ET
from difflib import get_close_matches

from rdflib import Graph, Namespace
from flask import Flask, render_template, jsonify, request

# os                          - Check whether the RDF .ttl file exists
# xml.etree.ElementTree as ET - Read XML file, especially skill names and aliases
# get_close_matches           - Suggest closest skill spelling, like pyhton → Python
# rdflib                      - Load and query the RDF Turtle graph
# Flask                       - Create the web application server
# render_template             - Serve HTML pages from the templates folder
# jsonify                     - Convert Python dictionaries to JSON API responses
# request                     - Read incoming data from the browser


# ------------------------------------------------------------
# TSW6223 Solution 2 Web Application
#
# Purpose:
# This file provides a modern web-based interface for the
# Semantic Career Path / Skill Gap Analyzer.
#
# The backend uses the same semantic technologies:
# - XML for skill aliases and input normalisation
# - RDF/RDFS Turtle file for semantic data
# - SPARQL queries to retrieve careers, required skills,
#   recommended courses, and alternative careers
#
# The web interface replaces the Tkinter GUI with a Flask
# server that serves a responsive HTML/CSS/JS dashboard.
# ------------------------------------------------------------


XML_FILE = "career_skill_data.xml"
TTL_FILE = "career_skill_graph.ttl"

# Reading XML with namespace.
XML_NS   = {"cs": "https://tsw6223.example.edu/career-skill"}

# RDF namespace for SPARQL queries.
EX       = Namespace("http://example.org/career-skill#")

# Create Flask application instance.
app = Flask(__name__)


# ============================================================
# Data Loading Functions
# ============================================================


def get_text(parent, tag_name):
    """
    Helper Function:
    Safely get text from an XML child element.
    This is mainly used to read skill names and aliases from XML.
    """
    element = parent.find(f"cs:{tag_name}", XML_NS)

    if element is not None and element.text is not None:
        return element.text.strip()

    return ""


def load_rdf_graph():
    """
    Load the generated RDF/RDFS Turtle graph.

    This graph is generated by xml_to_rdf.py and contains semantic
    relationships such as:
    - Career requires Skill
    - Course teaches Skill
    - Course has prerequisite Skill
    """
    if not os.path.exists(TTL_FILE):
        return None

    graph = Graph()
    graph.parse(TTL_FILE, format="turtle")
    return graph


def load_skill_aliases_from_xml():
    """
    Load official skill names and aliases from XML.

    Example:
    - "py" maps to "Python"
    - "ml" maps to "Machine Learning"
    - "pyhton" maps to "Python"

    This helps the system handle user input before SPARQL-based analysis.
    """
    tree = ET.parse(XML_FILE)
    root = tree.getroot()

    skill_names = []
    alias_map = {}

    for skill in root.findall("cs:skills/cs:skill", XML_NS):
        skill_name = get_text(skill, "skillName")
        skill_names.append(skill_name)

        # Map official skill name to itself.
        alias_map[skill_name.lower()] = skill_name

        # Map each alias to the official skill name.
        for alias in skill.findall("cs:aliases/cs:alias", XML_NS):
            if alias.text:
                alias_map[alias.text.strip().lower()] = skill_name

    return skill_names, alias_map


# ============================================================
# Input Processing Functions
# ============================================================


def clean_user_input(user_input):
    """
    Clean comma-separated skill input.

    Example:
    Input:  " pyhton, SQL, ml "
    Output: ["pyhton", "sql", "ml"]
    """
    cleaned_items = []

    for item in user_input.split(","):
        cleaned = item.strip().lower()

        if cleaned:
            cleaned_items.append(cleaned)

    return cleaned_items


def normalise_skills_for_web(user_input, skill_names, alias_map):
    """
    Convert user-entered skills into official skill names.

    Web version differences from the Tkinter GUI version:
    - Instead of showing a popup for fuzzy matches, the web version
      automatically accepts fuzzy corrections and returns them as
      corrections in the response for the frontend to display.
    - This makes the API stateless and suitable for JSON responses.
    """
    cleaned_inputs = clean_user_input(user_input)

    confirmed_skills = []
    unknown_skills = []
    corrections = []       # Stores fuzzy corrections made automatically.

    official_skill_lookup = {name.lower(): name for name in skill_names}
    official_skill_lowercase = list(official_skill_lookup.keys())

    for item in cleaned_inputs:

        # Exact alias match, e.g. "ml" -> "Machine Learning"
        if item in alias_map:
            official_skill = alias_map[item]

            if official_skill not in confirmed_skills:
                confirmed_skills.append(official_skill)

        else:
            # Fuzzy matching, e.g. "pythn" may suggest "Python"
            possible_matches = get_close_matches(
                item,
                official_skill_lowercase,
                n=1,
                cutoff=0.7
            )

            if possible_matches:
                suggested_skill = official_skill_lookup[possible_matches[0]]

                # Web version: auto-accept fuzzy corrections and report them.
                if suggested_skill not in confirmed_skills:
                    confirmed_skills.append(suggested_skill)

                corrections.append({
                    "original": item,
                    "corrected": suggested_skill
                })
            else:
                unknown_skills.append(item)

    return confirmed_skills, unknown_skills, corrections


# ============================================================
# SPARQL Query Functions
# ============================================================


def get_available_careers(graph):
    """
    Retrieve available careers from the RDF graph using SPARQL.
    """
    query = """
    PREFIX ex: <http://example.org/career-skill#>

    SELECT ?career ?careerName ?sourceTitle ?sourceCode ?careerLevel
    WHERE {
        ?career a ex:Career .
        ?career ex:careerName ?careerName .
        ?career ex:sourceOccupationTitle ?sourceTitle .
        ?career ex:sourceOccupationCode ?sourceCode .
        ?career ex:careerLevel ?careerLevel .
    }
    ORDER BY ?careerName
    """

    careers = []

    for row in graph.query(query):
        careers.append({
            "career_uri": str(row.career),
            "career_name": str(row.careerName),
            "source_title": str(row.sourceTitle),
            "source_code": str(row.sourceCode),
            "career_level": str(row.careerLevel)
        })

    return careers


def get_required_skills_for_career(graph, career_uri):
    """
    Retrieve required skills for the selected career using SPARQL.
    """
    query = """
    PREFIX ex: <http://example.org/career-skill#>

    SELECT ?skill ?skillName ?skillCategory ?priority
    WHERE {
        <CAREER_URI> ex:requiresSkill ?skill .

        ?skill ex:skillName ?skillName .

        ?skill ex:skillCategory ?skillCategory .

        ?requirement a ex:SkillRequirement .
        ?requirement ex:requirementForCareer <CAREER_URI> .
        ?requirement ex:requiresSkill ?skill .
        ?requirement ex:priority ?priority .
    }
    ORDER BY ?priority ?skillName
    """.replace("CAREER_URI", career_uri)

    required_skills = []

    for row in graph.query(query):
        required_skills.append({
            "skill_uri": str(row.skill),
            "skill_name": str(row.skillName),
            "category": str(row.skillCategory),
            "priority": str(row.priority)
        })

    return required_skills


def analyse_skill_gap(required_skills, confirmed_skills):
    """
    Compare confirmed user skills with SPARQL-retrieved required skills.
    """
    matched_skills = []
    missing_skills = []

    for skill in required_skills:
        if skill["skill_name"] in confirmed_skills:
            matched_skills.append(skill)
        else:
            missing_skills.append(skill)

    total_required = len(required_skills)
    total_matched = len(matched_skills)

    if total_required > 0:
        readiness_score = round((total_matched / total_required) * 100)
    else:
        readiness_score = 0

    return matched_skills, missing_skills, readiness_score


def get_courses_for_missing_skills(graph, missing_skills):
    """
    Retrieve recommended courses using SPARQL.

    This query uses the SPARQL VALUES clause to inject the missing skills
    directly into the query, filtering courses at the graph database level.
    """
    if not missing_skills:
        return []

    skill_names_str = " ".join([f'"{skill["skill_name"]}"' for skill in missing_skills])

    query = f"""
    PREFIX ex: <http://example.org/career-skill#>

    SELECT ?course ?courseName ?skillName ?prerequisiteName
    WHERE {{
        VALUES ?skillName {{ {skill_names_str} }}

        ?course a ex:Course .
        ?course ex:courseName ?courseName .
        ?course ex:teachesSkill ?skill .
        ?skill ex:skillName ?skillName .

        OPTIONAL {{
            ?course ex:prerequisiteSkill ?prerequisite .
            ?prerequisite ex:skillName ?prerequisiteName .
        }}
    }}
    ORDER BY ?courseName ?skillName
    """

    recommended = {}

    for row in graph.query(query):
        skill_name = str(row.skillName)
        course_uri = str(row.course)
        course_name = str(row.courseName)

        if course_uri not in recommended:
            recommended[course_uri] = {
                "course_name": course_name,
                "teaches_missing_skills": [],
                "prerequisite_skills": []
            }

        if skill_name not in recommended[course_uri]["teaches_missing_skills"]:
            recommended[course_uri]["teaches_missing_skills"].append(skill_name)

        if row.prerequisiteName:
            prerequisite_name = str(row.prerequisiteName)

            if prerequisite_name not in recommended[course_uri]["prerequisite_skills"]:
                recommended[course_uri]["prerequisite_skills"].append(prerequisite_name)

    return list(recommended.values())


def suggest_alternative_careers(graph, selected_career_uri, confirmed_skills):
    """
    Retrieve career-skill relationships using SPARQL and calculate
    match percentage for alternative careers.

    This query filters out the selected target career at the SPARQL graph level.
    """
    query = f"""
    PREFIX ex: <http://example.org/career-skill#>

    SELECT ?career ?careerName ?skillName
    WHERE {{
        ?career a ex:Career .
        ?career ex:careerName ?careerName .

        FILTER(?career != <{selected_career_uri}>)

        ?career ex:requiresSkill ?skill .
        ?skill ex:skillName ?skillName .
    }}
    ORDER BY ?careerName ?skillName
    """

    career_skill_map = {}

    for row in graph.query(query):
        career_uri = str(row.career)
        career_name = str(row.careerName)
        skill_name = str(row.skillName)

        if career_uri not in career_skill_map:
            career_skill_map[career_uri] = {
                "career_name": career_name,
                "required_skills": []
            }

        career_skill_map[career_uri]["required_skills"].append(skill_name)

    alternatives = []

    for career_uri, career_data in career_skill_map.items():
        required_skills = career_data["required_skills"]
        matched_count = 0

        for skill_name in required_skills:
            if skill_name in confirmed_skills:
                matched_count += 1

        if required_skills:
            match_score = round((matched_count / len(required_skills)) * 100)
        else:
            match_score = 0

        alternatives.append({
            "career_name": career_data["career_name"],
            "match_score": match_score
        })

    alternatives.sort(key=lambda item: item["match_score"], reverse=True)

    return alternatives


def group_missing_skills_by_priority(missing_skills):
    """
    Group missing skills into High, Medium, and Low priority.
    """
    grouped = {
        "High": [],
        "Medium": [],
        "Low": []
    }

    for skill in missing_skills:
        priority = skill["priority"]

        if priority in grouped:
            grouped[priority].append(skill)
        else:
            grouped["Low"].append(skill)

    return grouped


# ============================================================
# Flask Routes
# ============================================================


@app.route("/")
def index():
    """
    Serve the main web page.
    """
    return render_template("index.html")


@app.route("/api/careers")
def api_careers():
    """
    API endpoint: Return available careers from the RDF graph.

    Used by the frontend to populate the career dropdown.
    """
    graph = load_rdf_graph()

    if graph is None:
        return jsonify({"error": "RDF graph not found. Please run py main.py first."}), 500

    careers = get_available_careers(graph)

    return jsonify({"careers": careers})


@app.route("/api/skills")
def api_skills():
    """
    API endpoint: Return all official skill names.

    Used by the frontend for autocomplete suggestions.
    """
    skill_names, alias_map = load_skill_aliases_from_xml()

    return jsonify({
        "skill_names": skill_names,
        "alias_map": alias_map
    })


@app.route("/api/validate-skill")
def api_validate_skill():
    """
    API endpoint: Validate a single skill input and return the
    resolved official name, or a fuzzy suggestion if applicable.

    Used by the frontend tag input for real-time validation.
    """
    raw_input = request.args.get("skill", "").strip().lower()

    if not raw_input:
        return jsonify({"status": "empty"})

    skill_names, alias_map = load_skill_aliases_from_xml()

    official_skill_lookup = {name.lower(): name for name in skill_names}
    official_skill_lowercase = list(official_skill_lookup.keys())

    # Exact alias match
    if raw_input in alias_map:
        return jsonify({
            "status": "matched",
            "official_name": alias_map[raw_input]
        })

    # Fuzzy match
    possible_matches = get_close_matches(
        raw_input,
        official_skill_lowercase,
        n=1,
        cutoff=0.7
    )

    if possible_matches:
        suggested_skill = official_skill_lookup[possible_matches[0]]
        return jsonify({
            "status": "suggestion",
            "original": raw_input,
            "suggested": suggested_skill
        })

    return jsonify({
        "status": "unknown",
        "original": raw_input
    })


@app.route("/api/analyze", methods=["POST"])
def api_analyze():
    """
    API endpoint: Run the full skill gap analysis.

    Expects JSON body:
    {
        "career_uri": "http://example.org/career-skill#DataAnalyst",
        "skills": "pyhton, sql, ml"
    }

    Returns the complete analysis result as JSON.
    """
    data = request.get_json()

    if not data:
        return jsonify({"error": "No input data provided."}), 400

    career_uri = data.get("career_uri", "")
    skills_input = data.get("skills", "")

    if not career_uri:
        return jsonify({"error": "Please select a target career."}), 400

    if not skills_input.strip():
        return jsonify({"error": "Please enter at least one skill."}), 400

    # Load RDF graph
    graph = load_rdf_graph()

    if graph is None:
        return jsonify({"error": "RDF graph not found. Please run py main.py first."}), 500

    # Load skill aliases for input normalisation
    skill_names, alias_map = load_skill_aliases_from_xml()

    # Normalise user input
    confirmed_skills, unknown_skills, corrections = normalise_skills_for_web(
        skills_input,
        skill_names,
        alias_map
    )

    # Get career details
    careers = get_available_careers(graph)
    selected_career = None

    for career in careers:
        if career["career_uri"] == career_uri:
            selected_career = career
            break

    if selected_career is None:
        return jsonify({"error": "Selected career not found."}), 400

    # Run SPARQL-powered analysis
    required_skills = get_required_skills_for_career(graph, career_uri)

    matched_skills, missing_skills, readiness_score = analyse_skill_gap(
        required_skills,
        confirmed_skills
    )

    recommended_courses = get_courses_for_missing_skills(graph, missing_skills)

    alternative_careers = suggest_alternative_careers(
        graph,
        career_uri,
        confirmed_skills
    )

    grouped_missing = group_missing_skills_by_priority(missing_skills)

    # Return full analysis result as JSON
    return jsonify({
        "selected_career": selected_career,
        "confirmed_skills": confirmed_skills,
        "unknown_skills": unknown_skills,
        "corrections": corrections,
        "required_skills": required_skills,
        "matched_skills": matched_skills,
        "missing_skills": missing_skills,
        "grouped_missing": grouped_missing,
        "readiness_score": readiness_score,
        "recommended_courses": recommended_courses,
        "alternative_careers": alternative_careers
    })


# ============================================================
# Main Entry Point
# ============================================================


def main():
    """
    Start the Flask web application.

    The server runs on http://localhost:5000 by default.
    """
    print("\n==============================================")
    print(" TSW6223 Solution 2 - Web Interface")
    print(" Semantic Career Path / Skill Gap Analyzer")
    print("==============================================")
    print("\nStarting web server...")
    print("Open your browser and go to: http://localhost:5000")
    print("Press Ctrl+C to stop the server.\n")

    app.run(debug=True, port=5000)


if __name__ == "__main__":
    main()
